// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileGetArgs = { repo_id: string, path: string, 
/**
 * `None` → latest. `Some(n)` → that specific revision number.
 */
revision: number | null, };
