// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilePutArgs = { repo_id: string, 
/**
 * POSIX-style full path inside the repo (e.g. `notes/2026/may.md`).
 * Intermediate folders auto-created.
 */
path: string, 
/**
 * Base64-encoded payload. `gen-ts` emits this as `string` in TS;
 * callers (MCP, worker) agree on base64 for binary safety.
 */
content_base64: string, mime: string | null, 
/**
 * Optional commit message attached to the new revision.
 */
message: string | null, };
