// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type File = { id: string, repo_id: string, 
/**
 * `None` → file sits at repo root.
 */
folder_id: string | null, name: string, 
/**
 * Denormalized for search/index. `folder.path + "/" + name`, no leading slash.
 */
path: string, 
/**
 * `revisions.id` of the latest non-deleted revision. May be the deleted
 * row's id immediately after `file_delete` — clients should check
 * `deleted_at` first.
 */
current_revision_id: string, 
/**
 * `1` for the initial revision, monotonically incremented per `file_put`.
 */
current_revision_number: number, size: bigint, mime: string | null, created_at: string, updated_at: string, 
/**
 * RFC 3339 if soft-deleted; `None` for live files.
 */
deleted_at: string | null, };
