// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileSearchArgs = { repo_id: string, 
/**
 * Substring match against `files.path` and `files.name`. Phase 1 is a
 * SQL `LIKE`; Phase 2 may add full-text on `revisions.content_text`.
 */
query: string, 
/**
 * Restrict to this folder subtree (POSIX path). Default: whole repo.
 */
under_path: string | null, 
/**
 * Include soft-deleted files. Default false.
 */
include_deleted: boolean, 
/**
 * `1..=100`, default 20.
 */
limit: number | null, };
