// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileHistoryArgs = { repo_id: string, path: string, 
/**
 * `1..=100`, default 20.
 */
limit: number | null, };
