// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Folder = { id: string, repo_id: string, 
/**
 * `None` only for the implicit root folder (`path == ""`).
 */
parent_id: string | null, 
/**
 * Single-segment name. Cannot contain `/` or `\0`.
 */
name: string, 
/**
 * Full POSIX-style path from repo root, no leading slash. Root = `""`.
 */
path: string, created_at: string, };
