// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderListArgs = { repo_id: string, 
/**
 * Empty string = repo root. Otherwise the canonical `path` of the parent.
 */
path: string, 
/**
 * Recurse into subfolders. Default false.
 */
recursive: boolean, };
