// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { File } from "./File";
import type { Folder } from "./Folder";

/**
 * Response shape for `folder_list` — folders + files at (or under) `path`.
 */
export type FolderListing = { folders: Array<Folder>, files: Array<File>, };
