// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderCreateArgs = { repo_id: string, 
/**
 * POSIX-style path. Missing intermediate folders are created (mkdir -p).
 */
path: string, };
