// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Args for `repos_list` (MCP tool). Lists every repo owned by the
 * authenticated GitHub user.
 *
 * `name` is the discovery counterpart to `repo_init`'s idempotency: callers
 * can find the UUID of an existing repo without remembering what the worker
 * minted previously. Distinct from github-mcp-server-rs's `list_repos`
 * (GitHub API) — that's why this is named `repos_list`.
 */
export type ReposListArgs = Record<string, never>;
