// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Args for `repo_init` (MCP tool, Phase 1).
 *
 * Idempotent: if a repo with the same `(owner_login, name)` already exists,
 * the worker returns the existing row instead of erroring.
 */
export type RepoInitArgs = { 
/**
 * Repository slug. `[a-z0-9][a-z0-9._-]{0,62}`, validated server-side.
 */
name: string, };
