// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Revision = { id: string, file_id: string, 
/**
 * 1-indexed, monotonic per file.
 */
rev_number: number, 
/**
 * R2 key. Format: `files/{repo_id}/{file_id}/{rev_number}`.
 */
blob_key: string, size: bigint, 
/**
 * Lowercase hex SHA-256 of the raw (pre-base64) bytes.
 */
sha256: string, mime: string | null, 
/**
 * GitHub login that produced this revision (resolved from MCP JWT).
 */
author_login: string, message: string | null, created_at: string, };
