/**
 * ref-files-worker — HTTP facade for ref-files-mcp-server-rs.
 *
 * Composition only: middleware + sub-app mounts. Actual handlers live under
 * `src/routes/`, schema under `src/db/`, auth under `src/middleware/`.
 *
 * Each `/v1/*` route corresponds 1:1 to an MCP tool in
 * `ref-files-mcp-server-rs/src/tools/` (Phase 1). Wire-shape DTOs come from
 * `src/types/` (regenerated by `.github/workflows/sync-types.yml`).
 */
import { Hono } from "hono";

import type { AppEnv } from "./env";
import { mcpAuth } from "./middleware/auth";
import { files } from "./routes/files";
import { folders } from "./routes/folders";
import { repos } from "./routes/repos";

const app = new Hono<AppEnv>();

// Liveness — no auth, no DB hit.
app.get("/health", (c) =>
  c.json({ ok: true, env: c.env.WORKER_ENV, version: "0.1.0-phase0" }),
);

// JWT-required surface.
app.use("/v1/*", mcpAuth);
app.route("/v1/repos", repos);
app.route("/v1/folders", folders);
app.route("/v1/files", files);

app.notFound((c) => c.json({ error: "not_found" }, 404));

app.onError((err, c) => {
  console.error("[ref-files-worker]", err);
  return c.json({ error: "internal_error", message: err.message }, 500);
});

export default app;
